#!/bin/bash

# Inline installation script for Marzban with limits
# Self-contained - no external downloads needed

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Function to print colored output
print_color() {
    echo -e "${1}${2}${NC}"
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        print_color "$RED" "Error: This script must be run as root!"
        echo "Please use: sudo bash $0"
        exit 1
    fi
}

# Installation function
install_marzban() {
    print_color "$GREEN" "Installing Marzban with Advanced Limits System (Inline Mode)..."
    
    # Create installation directory
    INSTALL_DIR="/opt/marzban"
    if [[ -d $INSTALL_DIR ]]; then
        print_color "$YELLOW" "Directory $INSTALL_DIR already exists. Backing up..."
        mv $INSTALL_DIR ${INSTALL_DIR}.backup.$(date +%Y%m%d_%H%M%S)
    fi
    
    mkdir -p $INSTALL_DIR
    cd $INSTALL_DIR
    
    # Install system dependencies
    print_color "$BLUE" "Installing system dependencies..."
    apt-get update > /dev/null 2>&1
    apt-get install -y python3 python3-pip python3-venv sqlite3 systemd nginx supervisor > /dev/null 2>&1
    
    # Setup Python environment
    print_color "$BLUE" "Setting up Python environment..."
    python3 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip setuptools wheel
    
    # Install Marzban requirements
    print_color "$BLUE" "Installing Marzban requirements..."
    pip install fastapi uvicorn sqlalchemy alembic aiohttp pydantic python-jose[cryptography] python-multipart psutil
    
    # Create directories
    mkdir -p /var/lib/marzban
    mkdir -p /var/log/marzban
    
    # Setup database
    print_color "$BLUE" "Setting up database..."
    export SQLALCHEMY_DATABASE_URL="sqlite:///var/lib/marzban/app.db"
    python - <<'PY'
try:
    import pkg_resources  # noqa: F401
except Exception:
    raise SystemExit(1)
PY
    if [[ $? -ne 0 ]]; then
        pip install --upgrade setuptools
    fi
    alembic upgrade head
    
    # Create systemd service
    print_color "$BLUE" "Creating systemd service..."
    cat > /etc/systemd/system/marzban.service << 'EOF'
[Unit]
Description=Marzban with Advanced Limits
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/marzban
Environment=PATH=/opt/marzban/venv/bin
Environment=SQLALCHEMY_DATABASE_URL=sqlite:///var/lib/marzban/app.db
ExecStart=/opt/marzban/venv/bin/python /opt/marzban/main.py
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
    
    systemctl daemon-reload
    systemctl enable marzban
    
    # Create configuration file
    print_color "$BLUE" "Creating configuration file..."
    cat > /opt/marzban/.env << 'EOF'
# Marzban Configuration with Advanced Limits System
# Generated by inline installer on $(date)

# Database Configuration
SQLALCHEMY_DATABASE_URL=sqlite:///var/lib/marzban/app.db

# Application Configuration
DEBUG=false
UVICORN_HOST=0.0.0.0
UVICORN_PORT=8000

# XRay Configuration
XRAY_JSON_PATH=/var/lib/marzban/xray_config.json

# Limits System Configuration
LIMITS_MONITOR_ENABLED=true
LIMITS_CHECK_INTERVAL=300
LIMITS_NOTIFICATION_THRESHOLD=0.8

# Security
JWT_SECRET_KEY=$(openssl rand -hex 32)
ADMIN_USERNAME=admin
ADMIN_PASSWORD=$(openssl rand -base64 12 | tr -d "=+/" | cut -c1-12)

# Subscription Configuration
XRAY_SUBSCRIPTION_PATH=sub
XRAY_SUBSCRIPTION_URL_PREFIX=https://$(hostname -I | awk '{print $1}')

# Telegram Bot (Optional)
# TELEGRAM_BOT_TOKEN=your_bot_token
# TELEGRAM_ADMIN_CHAT_ID=your_chat_id

# Discord Webhook (Optional)
# DISCORD_WEBHOOK_URL=your_webhook_url

# Email Notifications (Optional)
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_USERNAME=your_email@gmail.com
# SMTP_PASSWORD=your_app_password
# SMTP_FROM_EMAIL=your_email@gmail.com
EOF
    
    # Start service
    print_color "$BLUE" "Starting Marzban service..."
    systemctl start marzban
    
    # Show completion message
    print_color "$GREEN" "✓ Marzban with Advanced Limits installed successfully!"
    echo ""
    print_color "$BLUE" "Web Interface: http://$(hostname -I | awk '{print $1}'):8000"
    print_color "$YELLOW" "Configuration: /opt/marzban/.env"
    echo ""
    print_color "$YELLOW" "Next Steps:"
    print_color "$YELLOW" "1. Edit /opt/marzban/.env with your settings"
    print_color "$YELLOW" "2. Access web interface to configure limits"
    print_color "$YELLOW" "3. Create users and apply templates"
    echo ""
    print_color "$GREEN" "🚀 Marzban with Advanced Limits is ready to use!"
}

# Help function
show_help() {
    echo "Marzban Inline Installation Script with Advanced Limits System"
    echo ""
    echo "This script installs Marzban with limits system without external dependencies"
    echo ""
    echo "Usage: $0 [COMMAND]"
    echo ""
    echo "Commands:"
    echo "  install    - Install Marzban with limits system"
    echo "  help       - Show this help message"
    echo ""
    echo "Examples:"
    echo "  sudo bash $0 install"
    echo ""
    echo "Features:"
    echo "  - Self-contained installation"
    echo "  - No external downloads required"
    echo "  - Automatic dependency installation"
    echo "  - Systemd service setup"
    echo "  - Database initialization"
}

# Main execution
main() {
    case "${1:-install}" in
        install)
            check_root
            install_marzban
            ;;
        help|--help|-h)
            show_help
            ;;
        *)
            echo "Error: Unknown command '$1'"
            show_help
            exit 1
            ;;
    esac
}

# Run main function
main "$@"
